AL5D:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - virtual_joint
      - base_pan
      - shoulder_tilt
      - elbow_tilt
      - wrist_tilt
      - wrist_rotate
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  al5d_arm_controller:
    type: joint_state_controller/JointStateController
    joints:
      - base_pan
      - shoulder_tilt
      - elbow_tilt
    gains:
      base_pan:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      shoulder_tilt:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      elbow_tilt:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  al5d_hand_controller:
    type: joint_state_controller/JointStateController
    joints:
      - wrist_tilt
      - wrist_rotate
    gains:
      wrist_tilt:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wrist_rotate:
        p: 100
        d: 1
        i: 1
        i_clamp: 1